version: "3.8"

services:
  backend:
    build: .
    container_name: fastify-ai-bot
    ports:
      - "5050:5000"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=development
